urls:
  fms_server: hercules-intb.ciscospark.com
  rd_server: remote-dispatcher-intb.ciscospark.com
  ci_broker_server: idbrokerbts.webex.com
  control_hub: int-admin.webex.com
connectors:
  expected_connectors: {c_mgmt: 'Management Connector', c_cal: 'Calendar Connector', c_imp: 'Message Connector', c_serab: 'Serviceability Connector'}
misc:
  # TODO: Get a client, this is e2e's one
  client_id: Ca779cc7acab70dade83b616c5d35a88909355ffe3090a6644d0fac4cf1fdb317
  client_secret: 7056e27320ad4a0f872e988f189f4090f33413efb94fbdeb72e007a82651c239
