#!/bin/bash


####################################################################################################################
################################################# Library pyc Removal Migration ####################################
####################################################################################################################
# This Section will fix old broken postrm scripts, that were deleting libraries' pyc files on upgrade
# US12647 - TechDebt: Remove sed on postrm

function fix_remove_all_pycs()
{
    postrm_path="/tandberg/tbl/dpkg/info/c_mgmt.postrm"
    sed -i 's/find -P .*/find -P \/opt\/c_mgmt\/xcommand\/ \/opt\/c_mgmt\/xstatus\/ -name \*.pyc | xargs rm -f/' ${postrm_path}
}
fix_remove_all_pycs

################################################# End Migration logic ##############################################