#!/bin/bash


####################################################################################################################
############################################## bin symlink to directory migration ##################################
####################################################################################################################
# Changing /opt/c_mgmt/bin from a symlink to a real file can sometimes fail and leave bin files in the
# ni python directory structure, delete it before installing the real bin directory

function remove_bin_directory_symlink()
{
    if [ -L /opt/c_mgmt/bin ]; then
        rm /opt/c_mgmt/bin
    fi
}
remove_bin_directory_symlink

################################################# End Migration logic ##############################################