#!/bin/bash

COREDUMPFILE="/tmp/request/copycoredumps"
COREDIR="/tmp/coredumps"

if [ -f ${COREDUMPFILE} ] ; then
    mkdir -p ${COREDIR}
    FILE_LOCATION=$(<${COREDUMPFILE})
    cp -r ${FILE_LOCATION} ${COREDIR}
    chown -hR _c_mgmt ${COREDIR}
    rm ${COREDUMPFILE}
fi
