#!/bin/bash

source /etc/functions

file_paths=($(ls /opt/))
file_paths=( ${file_paths[@]/#//tmp/request/} )
file_paths=( ${file_paths[@]/%/_hybrid_request} )

for file in "${file_paths[@]}"
do
    if [ -f ${file} ]; then

    contents=`cat ${file}`
    rm ${file}
    syslog_msg "Detail=\"Hybrid Request triggered by: ${file}\""

    # Python source can't have unexpected indents
    python <<END_PYTHON_PART
from ni.managementconnector.platform.hybridrequesthandler import on_request
from ni.managementconnector.config.databasehandler import DatabaseHandler
on_request(DatabaseHandler(), '${contents}')
END_PYTHON_PART
    fi
done