import unittest
import sys
import logging
import mock

from ni.managementconnector.config.certhandler import merge_certs, repair_certs

sys.path.append("/opt/c_mgmt/bin/")

from ni.managementconnector.config.managementconnectorproperties import ManagementConnectorProperties

DEV_LOGGER = ManagementConnectorProperties.get_dev_logger()


class CertHandlerTest(unittest.TestCase):
    """ CertHandler Test Class """
    data_before = '''-----BEGIN CERTIFICATE-----
MIIEPTCCAyWgAwIBAgIJAIoT80FOqKbvMA0GCSqGSIb3DQEBCwUAMIG0MTowOAYD
VQQKDDFUZW1wb3JhcnkgQ0EgZjEyMDE4NmItZDY5My00MWUzLTgxNzEtZDk3YzEx
M2E4YzUzMTowOAYDVQQLDDFUZW1wb3JhcnkgQ0EgZjEyMDE4NmItZDY5My00MWUz
LTgxNzEtZDk3YzExM2E4YzUzMTowOAYDVQQDDDFUZW1wb3JhcnkgQ0EgZjEyMDE4
NmItZDY5My00MWUzLTgxNzEtZDk3YzExM2E4YzUzMB4XDTE1MDcxMzE1NTkzN1oX
DTIwMDcxMTE1NTkzN1owgbQxOjA4BgNVBAoMMVRlbXBvcmFyeSBDQSBmMTIwMTg2
Yi1kNjkzLTQxZTMtODE3MS1kOTdjMTEzYThjNTMxOjA4BgNVBAsMMVRlbXBvcmFy
eSBDQSBmMTIwMTg2Yi1kNjkzLTQxZTMtODE3MS1kOTdjMTEzYThjNTMxOjA4BgNV
BAMMMVRlbXBvcmFyeSBDQSBmMTIwMTg2Yi1kNjkzLTQxZTMtODE3MS1kOTdjMTEz
YThjNTMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCvVbebQSrj1DxP
tnmOVL/oPbn7bur+JiEmLgR0No828TvvTpvgggffG0ek+uLI436EmoyqgRqKJOpH
97eZajQv+Rr+jbJxGg3wketD3eGZpRVUvakWxCY3hIyqXTDZ6ak7wmUaQPL8Qu7+
ZJl4Wz4hwBr8AQg+uZ0ksMz53Itl5Fi+VAHKy1kN9AWa0Fyo9WAnjreph2kvZkEK
KH0KmPnYOJDfndl0MZE+MlfbQBLLenxtw7l+6rxIZVqGyMsDjKVMYi6FN17oOrUP
a3TVEH6HZyBTEgL2ZecoxXhPSOihNbjhXLIDpItPKn754ZOmiPKfMI54aEUrzazE
Ufw4vVmxAgMBAAGjUDBOMB0GA1UdDgQWBBTK0TSSTk983PennvdXluo4IcJ5jDAf
BgNVHSMEGDAWgBTK0TSSTk983PennvdXluo4IcJ5jDAMBgNVHRMEBTADAQH/MA0G
CSqGSIb3DQEBCwUAA4IBAQA+pd3DfDl6acfd3WUfLsfQlpi83v8ng4fXKtgXsHoZ
2zIxRoqQVIkUsGIy1fgekINLOVf0bXyfaWmBqOZ4f0yuitB5P6KV9Ns4JGTh/Fha
1sz0b1BPvvoWIVCa2qcA4h7ks2tqZIGw2VHtBjkwNdZh5TU5++H0uiLqyYRsQCZ3
6e/it5piDHTjB8632VLSlJyPC77umcQAt8pGS5rWNmuTVpthDryqknoFbnhwTCxo
kRe+kZRBxiKyWiUDvNk30Kw6G2wDgLUEMgn5F6nEp1zm+Xu1GToub0X98jO9Js6K
zD70vNxlnDNhdnI/f+GY4XUnfnCvxScXKlbI7rzaz8TR
-----END CERTIFICATE-----





O=Cisco, CN=cafe-test.cisco.com
-----BEGIN CERTIFICATE-----
MIIDojCCAooCCQDzorQEUQTlpjANBgkqhkiG9w0BAQsFADCBkjELMAkGA1UEBhMC
SUUxEjAQBgNVBAgMCUNvbm5hdWdodDEPMA0GA1UEBwwGR2Fsd2F5MQ4wDAYDVQQK
DAVDaXNjbzENMAsGA1UECwwERWRnZTEcMBoGA1UEAwwTY2FmZS10ZXN0LmNpc2Nv
LmNvbTEhMB8GCSqGSIb3DQEJARYSbWFybmV3ZWxAY2lzY28uY29tMB4XDTE1MDMx
OTE0MzQxOVoXDTE2MDMxODE0MzQxOVowgZIxCzAJBgNVBAYTAklFMRIwEAYDVQQI
DAlDb25uYXVnaHQxDzANBgNVBAcMBkdhbHdheTEOMAwGA1UECgwFQ2lzY28xDTAL
BgNVBAsMBEVkZ2UxHDAaBgNVBAMME2NhZmUtdGVzdC5jaXNjby5jb20xITAfBgkq
hkiG9w0BCQEWEm1hcm5ld2VsQGNpc2NvLmNvbTCCASIwDQYJKoZIhvcNAQEBBQAD
ggEPADCCAQoCggEBAMKuhMwUwF1FGRFdLsfGDthetyxcAD9rqviK0vA2yuvtUDS8
s0HmNSTnZrwV4iUCEtXpl4rwxvNCMJZCd2boHB/K4Mwc9kw6au7keq1JPbCciQWf
9wiFKhEryl5agWvJ2wfHXv2aKE4bvc831TThrb66SEgkz0pB3x1QFyGH62YAkqt1
QB69uZ4ZO3LcTqPyYLW+nbCe8lpFQtDlPal2h9sTRoWFiERwgivcbn2TDx2ByWzz
etAObv+vlVP/v33xp0to3ai5SOSoWwF8i0e5MidJnX5dqHeUwxWYxzo8MVkeDFj+
1HV3jIykHhEKw/1R6DQeiOrFestSSb5ZFijTyjkCAwEAATANBgkqhkiG9w0BAQsF
AAOCAQEAslEeMeURJWJCzuXaaRabSs2YW6gAJcm7gREnFFo4iaTBplLqT8No7O7R
h2PydZC7o0liTXECYJLGHqHZqwcmaryQUVtx22XxMa1kFGjCFcKMK+bO89TyXLqx
kQ/Np+ub0JFcf3+2X5iKTvU39XvpweLP8oj+b6XPqr0yt0eAgpIQQ/ituOlKrWW8
QzsGJqx96YuQaTt/SI6BgKKzN2+QxZvWj7DHv4a25IRiWs1bpQ0Y39zoYkH474UJ
5vl8w//hhsHtzSX8FSgyEBugRXaN9E0TopKluxDhyHb71l2h6Pd10oYAYI39V4ak
BL+vhInEG6aCpktbInf2K3L1JEni7g==
-----END CERTIFICATE-----
O=GTE Corporation, CN=GTE CyberTrust Global Root
-----BEGIN CERTIFICATE-----
MIICWjCCAcMCAgGlMA0GCSqGSIb3DQEBBAUAMHUxCzAJBgNVBAYTAlVTMRgwFgYD
VQQKEw9HVEUgQ29ycG9yYXRpb24xJzAlBgNVBAsTHkdURSBDeWJlclRydXN0IFNv
bHV0aW9ucywgSW5jLjEjMCEGA1UEAxMaR1RFIEN5YmVyVHJ1c3QgR2xvYmFsIFJv
b3QwHhcNOTgwODEzMDAyOTAwWhcNMTgwODEzMjM1OTAwWjB1MQswCQYDVQQGEwJV
UzEYMBYGA1UEChMPR1RFIENvcnBvcmF0aW9uMScwJQYDVQQLEx5HVEUgQ3liZXJU
cnVzdCBTb2x1dGlvbnMsIEluYy4xIzAhBgNVBAMTGkdURSBDeWJlclRydXN0IEds
b2JhbCBSb290MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCVD6C28FCc6HrH
iM3dFw4usJTQGz0O9pTAipTHBsiQl8i4ZBp6fmw8U+E3KHNgf7KXUwefU/ltWJTS
r41tiGeA5u2ylc9yMcqlHHK6XALnZELn+aks1joNrI1CqiQBOeacPwGFVw1Yh0X4
04Wqk2kmhXBIgD8SFcd5tB8FLztimQIDAQABMA0GCSqGSIb3DQEBBAUAA4GBAG3r
GwnpXtlR22ciYaQqPEh346B8pt5zohQDhT37qw4wxYMWM4ETCJ57NE7fQMh017l9
3PR2VX2bY1QY6fDq81yx2YtCHrnAlU66+tXifPVoYb+O7AWXX1uw16OFNMQkpw0P
lZPvy5TYnh+dXIVtx6quTx8itc2VrbqnzPmrC3p/
-----END CERTIFICATE-----




O=GoDaddy.com, Inc., CN=Go Daddy Root Certificate Authority - G2
-----BEGIN CERTIFICATE-----
MIIDxTCCAq2gAwIBAgIBADANBgkqhkiG9w0BAQsFADCBgzELMAkGA1UEBhMCVVMx
EDAOBgNVBAgTB0FyaXpvbmExEzARBgNVBAcTClNjb3R0c2RhbGUxGjAYBgNVBAoT
EUdvRGFkZHkuY29tLCBJbmMuMTEwLwYDVQQDEyhHbyBEYWRkeSBSb290IENlcnRp
ZmljYXRlIEF1dGhvcml0eSAtIEcyMB4XDTA5MDkwMTAwMDAwMFoXDTM3MTIzMTIz
NTk1OVowgYMxCzAJBgNVBAYTAlVTMRAwDgYDVQQIEwdBcml6b25hMRMwEQYDVQQH
EwpTY290dHNkYWxlMRowGAYDVQQKExFHb0RhZGR5LmNvbSwgSW5jLjExMC8GA1UE
AxMoR28gRGFkZHkgUm9vdCBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkgLSBHMjCCASIw
DQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAL9xYgjx+lk09xvJGKP3gElY6SKD
E6bFIEMBO4Tx5oVJnyfq9oQbTqC023CYxzIBsQU+B07u9PpPL1kwIuerGVZr4oAH
/PMWdYA5UXvl+TW2dE6pjYIT5LY/qQOD+qK+ihVqf94Lw7YZFAXK6sOoBJQ7Rnwy
DfMAZiLIjWltNowRGLfTshxgtDj6AozO091GB94KPutdfMh8+7ArU6SSYmlRJQVh
GkSBjCypQ5Yj36w6gZoOKcUcqeldHraenjAKOc7xiID7S13MMuyFYkMlNAJWJwGR
tDtwKj9useiciAF9n9T521NtYJ2/LOdYq7hfRvzOxBsDPAnrSTFcaUaz4EcCAwEA
AaNCMEAwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAQYwHQYDVR0OBBYE
FDqahQcQZyi27/a9BUFuIMGU2g/eMA0GCSqGSIb3DQEBCwUAA4IBAQCZ21151fmX
WWcDYfF+OwYxdS2hII5PZYe096acvNjpL9DbWu7PdIxztDhC2gV7+AJ1uP2lsdeu
9tfeE8tTEH6KRtGX+rcuKxGrkLAngPnon1rpN5+r5N9ss4UXnT3ZJE95kTXWXwTr
gIOrmgIttRD02JDHBHNA7XIloKmf7J6raBKZV8aPEjoJpL1E/QYVN8Gb5DKj7Tjo
2GTzLH4U/ALqn83/B2gX2yKQOC16jdFU8WnjXzPKej17CuPKf1855eJ1usV2GDPO
LPAvTK33sefOT6jEm0pUBsV/fdUID+Ic/n4XuKxe9tQWskMJDE32p2u0mYRlynqI
4uJEvlz36hz1
-----END CERTIFICATE-----
-----BEGIN X509 CRL-----
MIIDFDCCAfwCAQEwDQYJKoZIhvcNAQEFBQAwXzEjMCEGA1UEChMaU2FtcGxlIFNp
Z25lciBPcmdhbml6YXRpb24xGzAZBgNVBAsTElNhbXBsZSBTaWduZXIgVW5pdDEb
MBkGA1UEAxMSU2FtcGxlIFNpZ25lciBDZXJ0Fw0xMzAyMTgxMDMyMDBaFw0xMzAy
MTgxMDQyMDBaMIIBNjA8AgMUeUcXDTEzMDIxODEwMjIxMlowJjAKBgNVHRUEAwoB
AzAYBgNVHRgEERgPMjAxMzAyMTgxMDIyMDBaMDwCAxR5SBcNMTMwMjE4MTAyMjIy
WjAmMAoGA1UdFQQDCgEGMBgGA1UdGAQRGA8yMDEzMDIxODEwMjIwMFowPAIDFHlJ
Fw0xMzAyMTgxMDIyMzJaMCYwCgYDVR0VBAMKAQQwGAYDVR0YBBEYDzIwMTMwMjE4
MTAyMjAwWjA8AgMUeUoXDTEzMDIxODEwMjI0MlowJjAKBgNVHRUEAwoBATAYBgNV
HRgEERgPMjAxMzAyMTgxMDIyMDBaMDwCAxR5SxcNMTMwMjE4MTAyMjUxWjAmMAoG
A1UdFQQDCgEFMBgGA1UdGAQRGA8yMDEzMDIxODEwMjIwMFqgLzAtMB8GA1UdIwQY
MBaAFL4SAcyq6hGA2i6tsurHtfuf+a00MAoGA1UdFAQDAgEDMA0GCSqGSIb3DQEB
BQUAA4IBAQBCIb6B8cN5dmZbziETimiotDy+FsOvS93LeDWSkNjXTG/+bGgnrm3a
QpgB7heT8L2o7s2QtjX2DaTOSYL3nZ/Ibn/R8S0g+EbNQxdk5/la6CERxiRp+E2T
UG8LDb14YVMhRGKvCguSIyUG0MwGW6waqVtd6K71u7vhIU/Tidf6ZSdsTMhpPPFu
PUid4j29U3q10SGFF6cCt1DzjvUcCwHGhHA02Men70EgZFADPLWmLg0HglKUh1iZ
WcBGtev/8VsUijyjsM072C6Ut5TwNyrrthb952+eKlmxLNgT0o5hVYxjXhtwLQsL
7QZhrypAM1DLYqQjkiDI7hlvt7QuDGTJ
-----END X509 CRL-----

O=VeriSign, Inc.
-----BEGIN CERTIFICATE-----
MIICPDCCAaUCEHC65B0Q2Sk0tjjKewPMur8wDQYJKoZIhvcNAQECBQAwXzELMAkG
A1UEBhMCVVMxFzAVBgNVBAoTDlZlcmlTaWduLCBJbmMuMTcwNQYDVQQLEy5DbGFz
cyAzIFB1YmxpYyBQcmltYXJ5IENlcnRpZmljYXRpb24gQXV0aG9yaXR5MB4XDTk2
MDEyOTAwMDAwMFoXDTI4MDgwMTIzNTk1OVowXzELMAkGA1UEBhMCVVMxFzAVBgNV
BAoTDlZlcmlTaWduLCBJbmMuMTcwNQYDVQQLEy5DbGFzcyAzIFB1YmxpYyBQcmlt
YXJ5IENlcnRpZmljYXRpb24gQXV0aG9yaXR5MIGfMA0GCSqGSIb3DQEBAQUAA4GN
ADCBiQKBgQDJXFme8huKARS0EN8EQNvjV69qRUCPhAwL0TPZ2RHP7gJYHyX3KqhE
BarsAx94f56TuZoAqiN91qyFomNFx3InzPRMxnVx0jnvT0Lwdd8KkMaOIG+YD/is
I19wKTakyYbnsZogy1Olhec9vn2a/iRFM9x2Fe0PonFkTGUugWhFpwIDAQABMA0G
CSqGSIb3DQEBAgUAA4GBALtMEivPLCYATxQT3ab7/AoRhIzzKBxnki98tsX63/Do
lbwdj2wsqFHMc9ikwFPwTtYmwHYBV4GSXiHx0bH/59AhWM1pF+NEHJwZRDmJXNyc
AA9WjQKZ7aKQRUzkuxCkPfAyAw7xzvjoyVGM5mKf5p/AfbdynMk2OmufTqj/ZA1k
-----END CERTIFICATE-----

    '''

    data_after = '''-----BEGIN CERTIFICATE-----
MIIEPTCCAyWgAwIBAgIJAIoT80FOqKbvMA0GCSqGSIb3DQEBCwUAMIG0MTowOAYD
VQQKDDFUZW1wb3JhcnkgQ0EgZjEyMDE4NmItZDY5My00MWUzLTgxNzEtZDk3YzEx
M2E4YzUzMTowOAYDVQQLDDFUZW1wb3JhcnkgQ0EgZjEyMDE4NmItZDY5My00MWUz
LTgxNzEtZDk3YzExM2E4YzUzMTowOAYDVQQDDDFUZW1wb3JhcnkgQ0EgZjEyMDE4
NmItZDY5My00MWUzLTgxNzEtZDk3YzExM2E4YzUzMB4XDTE1MDcxMzE1NTkzN1oX
DTIwMDcxMTE1NTkzN1owgbQxOjA4BgNVBAoMMVRlbXBvcmFyeSBDQSBmMTIwMTg2
Yi1kNjkzLTQxZTMtODE3MS1kOTdjMTEzYThjNTMxOjA4BgNVBAsMMVRlbXBvcmFy
eSBDQSBmMTIwMTg2Yi1kNjkzLTQxZTMtODE3MS1kOTdjMTEzYThjNTMxOjA4BgNV
BAMMMVRlbXBvcmFyeSBDQSBmMTIwMTg2Yi1kNjkzLTQxZTMtODE3MS1kOTdjMTEz
YThjNTMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCvVbebQSrj1DxP
tnmOVL/oPbn7bur+JiEmLgR0No828TvvTpvgggffG0ek+uLI436EmoyqgRqKJOpH
97eZajQv+Rr+jbJxGg3wketD3eGZpRVUvakWxCY3hIyqXTDZ6ak7wmUaQPL8Qu7+
ZJl4Wz4hwBr8AQg+uZ0ksMz53Itl5Fi+VAHKy1kN9AWa0Fyo9WAnjreph2kvZkEK
KH0KmPnYOJDfndl0MZE+MlfbQBLLenxtw7l+6rxIZVqGyMsDjKVMYi6FN17oOrUP
a3TVEH6HZyBTEgL2ZecoxXhPSOihNbjhXLIDpItPKn754ZOmiPKfMI54aEUrzazE
Ufw4vVmxAgMBAAGjUDBOMB0GA1UdDgQWBBTK0TSSTk983PennvdXluo4IcJ5jDAf
BgNVHSMEGDAWgBTK0TSSTk983PennvdXluo4IcJ5jDAMBgNVHRMEBTADAQH/MA0G
CSqGSIb3DQEBCwUAA4IBAQA+pd3DfDl6acfd3WUfLsfQlpi83v8ng4fXKtgXsHoZ
2zIxRoqQVIkUsGIy1fgekINLOVf0bXyfaWmBqOZ4f0yuitB5P6KV9Ns4JGTh/Fha
1sz0b1BPvvoWIVCa2qcA4h7ks2tqZIGw2VHtBjkwNdZh5TU5++H0uiLqyYRsQCZ3
6e/it5piDHTjB8632VLSlJyPC77umcQAt8pGS5rWNmuTVpthDryqknoFbnhwTCxo
kRe+kZRBxiKyWiUDvNk30Kw6G2wDgLUEMgn5F6nEp1zm+Xu1GToub0X98jO9Js6K
zD70vNxlnDNhdnI/f+GY4XUnfnCvxScXKlbI7rzaz8TR
-----END CERTIFICATE-----

O=Cisco, CN=cafe-test.cisco.com
-----BEGIN CERTIFICATE-----
MIIDojCCAooCCQDzorQEUQTlpjANBgkqhkiG9w0BAQsFADCBkjELMAkGA1UEBhMC
SUUxEjAQBgNVBAgMCUNvbm5hdWdodDEPMA0GA1UEBwwGR2Fsd2F5MQ4wDAYDVQQK
DAVDaXNjbzENMAsGA1UECwwERWRnZTEcMBoGA1UEAwwTY2FmZS10ZXN0LmNpc2Nv
LmNvbTEhMB8GCSqGSIb3DQEJARYSbWFybmV3ZWxAY2lzY28uY29tMB4XDTE1MDMx
OTE0MzQxOVoXDTE2MDMxODE0MzQxOVowgZIxCzAJBgNVBAYTAklFMRIwEAYDVQQI
DAlDb25uYXVnaHQxDzANBgNVBAcMBkdhbHdheTEOMAwGA1UECgwFQ2lzY28xDTAL
BgNVBAsMBEVkZ2UxHDAaBgNVBAMME2NhZmUtdGVzdC5jaXNjby5jb20xITAfBgkq
hkiG9w0BCQEWEm1hcm5ld2VsQGNpc2NvLmNvbTCCASIwDQYJKoZIhvcNAQEBBQAD
ggEPADCCAQoCggEBAMKuhMwUwF1FGRFdLsfGDthetyxcAD9rqviK0vA2yuvtUDS8
s0HmNSTnZrwV4iUCEtXpl4rwxvNCMJZCd2boHB/K4Mwc9kw6au7keq1JPbCciQWf
9wiFKhEryl5agWvJ2wfHXv2aKE4bvc831TThrb66SEgkz0pB3x1QFyGH62YAkqt1
QB69uZ4ZO3LcTqPyYLW+nbCe8lpFQtDlPal2h9sTRoWFiERwgivcbn2TDx2ByWzz
etAObv+vlVP/v33xp0to3ai5SOSoWwF8i0e5MidJnX5dqHeUwxWYxzo8MVkeDFj+
1HV3jIykHhEKw/1R6DQeiOrFestSSb5ZFijTyjkCAwEAATANBgkqhkiG9w0BAQsF
AAOCAQEAslEeMeURJWJCzuXaaRabSs2YW6gAJcm7gREnFFo4iaTBplLqT8No7O7R
h2PydZC7o0liTXECYJLGHqHZqwcmaryQUVtx22XxMa1kFGjCFcKMK+bO89TyXLqx
kQ/Np+ub0JFcf3+2X5iKTvU39XvpweLP8oj+b6XPqr0yt0eAgpIQQ/ituOlKrWW8
QzsGJqx96YuQaTt/SI6BgKKzN2+QxZvWj7DHv4a25IRiWs1bpQ0Y39zoYkH474UJ
5vl8w//hhsHtzSX8FSgyEBugRXaN9E0TopKluxDhyHb71l2h6Pd10oYAYI39V4ak
BL+vhInEG6aCpktbInf2K3L1JEni7g==
-----END CERTIFICATE-----

O=GTE Corporation, CN=GTE CyberTrust Global Root
-----BEGIN CERTIFICATE-----
MIICWjCCAcMCAgGlMA0GCSqGSIb3DQEBBAUAMHUxCzAJBgNVBAYTAlVTMRgwFgYD
VQQKEw9HVEUgQ29ycG9yYXRpb24xJzAlBgNVBAsTHkdURSBDeWJlclRydXN0IFNv
bHV0aW9ucywgSW5jLjEjMCEGA1UEAxMaR1RFIEN5YmVyVHJ1c3QgR2xvYmFsIFJv
b3QwHhcNOTgwODEzMDAyOTAwWhcNMTgwODEzMjM1OTAwWjB1MQswCQYDVQQGEwJV
UzEYMBYGA1UEChMPR1RFIENvcnBvcmF0aW9uMScwJQYDVQQLEx5HVEUgQ3liZXJU
cnVzdCBTb2x1dGlvbnMsIEluYy4xIzAhBgNVBAMTGkdURSBDeWJlclRydXN0IEds
b2JhbCBSb290MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCVD6C28FCc6HrH
iM3dFw4usJTQGz0O9pTAipTHBsiQl8i4ZBp6fmw8U+E3KHNgf7KXUwefU/ltWJTS
r41tiGeA5u2ylc9yMcqlHHK6XALnZELn+aks1joNrI1CqiQBOeacPwGFVw1Yh0X4
04Wqk2kmhXBIgD8SFcd5tB8FLztimQIDAQABMA0GCSqGSIb3DQEBBAUAA4GBAG3r
GwnpXtlR22ciYaQqPEh346B8pt5zohQDhT37qw4wxYMWM4ETCJ57NE7fQMh017l9
3PR2VX2bY1QY6fDq81yx2YtCHrnAlU66+tXifPVoYb+O7AWXX1uw16OFNMQkpw0P
lZPvy5TYnh+dXIVtx6quTx8itc2VrbqnzPmrC3p/
-----END CERTIFICATE-----

O=GoDaddy.com, Inc., CN=Go Daddy Root Certificate Authority - G2
-----BEGIN CERTIFICATE-----
MIIDxTCCAq2gAwIBAgIBADANBgkqhkiG9w0BAQsFADCBgzELMAkGA1UEBhMCVVMx
EDAOBgNVBAgTB0FyaXpvbmExEzARBgNVBAcTClNjb3R0c2RhbGUxGjAYBgNVBAoT
EUdvRGFkZHkuY29tLCBJbmMuMTEwLwYDVQQDEyhHbyBEYWRkeSBSb290IENlcnRp
ZmljYXRlIEF1dGhvcml0eSAtIEcyMB4XDTA5MDkwMTAwMDAwMFoXDTM3MTIzMTIz
NTk1OVowgYMxCzAJBgNVBAYTAlVTMRAwDgYDVQQIEwdBcml6b25hMRMwEQYDVQQH
EwpTY290dHNkYWxlMRowGAYDVQQKExFHb0RhZGR5LmNvbSwgSW5jLjExMC8GA1UE
AxMoR28gRGFkZHkgUm9vdCBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkgLSBHMjCCASIw
DQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAL9xYgjx+lk09xvJGKP3gElY6SKD
E6bFIEMBO4Tx5oVJnyfq9oQbTqC023CYxzIBsQU+B07u9PpPL1kwIuerGVZr4oAH
/PMWdYA5UXvl+TW2dE6pjYIT5LY/qQOD+qK+ihVqf94Lw7YZFAXK6sOoBJQ7Rnwy
DfMAZiLIjWltNowRGLfTshxgtDj6AozO091GB94KPutdfMh8+7ArU6SSYmlRJQVh
GkSBjCypQ5Yj36w6gZoOKcUcqeldHraenjAKOc7xiID7S13MMuyFYkMlNAJWJwGR
tDtwKj9useiciAF9n9T521NtYJ2/LOdYq7hfRvzOxBsDPAnrSTFcaUaz4EcCAwEA
AaNCMEAwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAQYwHQYDVR0OBBYE
FDqahQcQZyi27/a9BUFuIMGU2g/eMA0GCSqGSIb3DQEBCwUAA4IBAQCZ21151fmX
WWcDYfF+OwYxdS2hII5PZYe096acvNjpL9DbWu7PdIxztDhC2gV7+AJ1uP2lsdeu
9tfeE8tTEH6KRtGX+rcuKxGrkLAngPnon1rpN5+r5N9ss4UXnT3ZJE95kTXWXwTr
gIOrmgIttRD02JDHBHNA7XIloKmf7J6raBKZV8aPEjoJpL1E/QYVN8Gb5DKj7Tjo
2GTzLH4U/ALqn83/B2gX2yKQOC16jdFU8WnjXzPKej17CuPKf1855eJ1usV2GDPO
LPAvTK33sefOT6jEm0pUBsV/fdUID+Ic/n4XuKxe9tQWskMJDE32p2u0mYRlynqI
4uJEvlz36hz1
-----END CERTIFICATE-----

-----BEGIN X509 CRL-----
MIIDFDCCAfwCAQEwDQYJKoZIhvcNAQEFBQAwXzEjMCEGA1UEChMaU2FtcGxlIFNp
Z25lciBPcmdhbml6YXRpb24xGzAZBgNVBAsTElNhbXBsZSBTaWduZXIgVW5pdDEb
MBkGA1UEAxMSU2FtcGxlIFNpZ25lciBDZXJ0Fw0xMzAyMTgxMDMyMDBaFw0xMzAy
MTgxMDQyMDBaMIIBNjA8AgMUeUcXDTEzMDIxODEwMjIxMlowJjAKBgNVHRUEAwoB
AzAYBgNVHRgEERgPMjAxMzAyMTgxMDIyMDBaMDwCAxR5SBcNMTMwMjE4MTAyMjIy
WjAmMAoGA1UdFQQDCgEGMBgGA1UdGAQRGA8yMDEzMDIxODEwMjIwMFowPAIDFHlJ
Fw0xMzAyMTgxMDIyMzJaMCYwCgYDVR0VBAMKAQQwGAYDVR0YBBEYDzIwMTMwMjE4
MTAyMjAwWjA8AgMUeUoXDTEzMDIxODEwMjI0MlowJjAKBgNVHRUEAwoBATAYBgNV
HRgEERgPMjAxMzAyMTgxMDIyMDBaMDwCAxR5SxcNMTMwMjE4MTAyMjUxWjAmMAoG
A1UdFQQDCgEFMBgGA1UdGAQRGA8yMDEzMDIxODEwMjIwMFqgLzAtMB8GA1UdIwQY
MBaAFL4SAcyq6hGA2i6tsurHtfuf+a00MAoGA1UdFAQDAgEDMA0GCSqGSIb3DQEB
BQUAA4IBAQBCIb6B8cN5dmZbziETimiotDy+FsOvS93LeDWSkNjXTG/+bGgnrm3a
QpgB7heT8L2o7s2QtjX2DaTOSYL3nZ/Ibn/R8S0g+EbNQxdk5/la6CERxiRp+E2T
UG8LDb14YVMhRGKvCguSIyUG0MwGW6waqVtd6K71u7vhIU/Tidf6ZSdsTMhpPPFu
PUid4j29U3q10SGFF6cCt1DzjvUcCwHGhHA02Men70EgZFADPLWmLg0HglKUh1iZ
WcBGtev/8VsUijyjsM072C6Ut5TwNyrrthb952+eKlmxLNgT0o5hVYxjXhtwLQsL
7QZhrypAM1DLYqQjkiDI7hlvt7QuDGTJ
-----END X509 CRL-----

O=VeriSign, Inc.
-----BEGIN CERTIFICATE-----
MIICPDCCAaUCEHC65B0Q2Sk0tjjKewPMur8wDQYJKoZIhvcNAQECBQAwXzELMAkG
A1UEBhMCVVMxFzAVBgNVBAoTDlZlcmlTaWduLCBJbmMuMTcwNQYDVQQLEy5DbGFz
cyAzIFB1YmxpYyBQcmltYXJ5IENlcnRpZmljYXRpb24gQXV0aG9yaXR5MB4XDTk2
MDEyOTAwMDAwMFoXDTI4MDgwMTIzNTk1OVowXzELMAkGA1UEBhMCVVMxFzAVBgNV
BAoTDlZlcmlTaWduLCBJbmMuMTcwNQYDVQQLEy5DbGFzcyAzIFB1YmxpYyBQcmlt
YXJ5IENlcnRpZmljYXRpb24gQXV0aG9yaXR5MIGfMA0GCSqGSIb3DQEBAQUAA4GN
ADCBiQKBgQDJXFme8huKARS0EN8EQNvjV69qRUCPhAwL0TPZ2RHP7gJYHyX3KqhE
BarsAx94f56TuZoAqiN91qyFomNFx3InzPRMxnVx0jnvT0Lwdd8KkMaOIG+YD/is
I19wKTakyYbnsZogy1Olhec9vn2a/iRFM9x2Fe0PonFkTGUugWhFpwIDAQABMA0G
CSqGSIb3DQEBAgUAA4GBALtMEivPLCYATxQT3ab7/AoRhIzzKBxnki98tsX63/Do
lbwdj2wsqFHMc9ikwFPwTtYmwHYBV4GSXiHx0bH/59AhWM1pF+NEHJwZRDmJXNyc
AA9WjQKZ7aKQRUzkuxCkPfAyAw7xzvjoyVGM5mKf5p/AfbdynMk2OmufTqj/ZA1k
-----END CERTIFICATE-----'''

    def setUp(self):
        """ CertHandler Test Setup """

        DEV_LOGGER.debug('***TEST Setup***')

    @mock.patch('__builtin__.open')
    def test_repair_certs(self, mock_file):
        """ Repair Certs Test """

        mock.mock_open(mock_file, read_data=self.data_before)

        repair_certs()

        mock_file.assert_has_calls([mock.call(ManagementConnectorProperties.COMBINED_CA_FILE, "rU"),
                                    mock.call(ManagementConnectorProperties.COMBINED_CA_FILE, "w")],
                                   any_order=True)
        mock_write = mock_file()
        mock_write.write.assert_has_calls([mock.call().write('\n' + c + '\n') for c in self.data_after.split('\n\n')],
                                          any_order=False)

    @mock.patch('ni.managementconnector.config.certhandler.repair_certs')
    @mock.patch('shutil.copyfileobj')
    @mock.patch('__builtin__.open', create=True)
    def test_merge_certs(self, mock_file, mock_shutil, mock_repair):
        """ Merge Certs Test """

        mock.mock_open(mock_file)

        # test with two files
        merge_certs(["test_infile1.txt", "test_infile2.txt"], "test_outfile.txt")

        mock_file.assert_has_calls([mock.call("test_infile1.txt", "rb"),
                                    mock.call("test_infile2.txt", "rb"),
                                    mock.call("test_outfile.txt", "wb")],
                                   any_order=True)

        mock_repair.assert_called_once()

        mock_file.reset_mock
        mock_repair.reset_mock

        # test with one files
        merge_certs(["test_infile1.txt"], "test_outfile.txt")

        mock_file.assert_has_calls([mock.call("test_infile1.txt", "rb"),
                                    mock.call("test_outfile.txt", "wb")],
                                   any_order=True)
        self.assertEqual(mock_repair.call_count, 2, "It should have been called twice")


if __name__ == "__main__":
    logging.basicConfig(level=logging.DEBUG)
    unittest.main()
